# Generated by Django 4.1.5 on 2023-02-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogApp", "0002_blogcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
